baseURL: "https://www.urutva.com/"
title: Devaraj Ranganna
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: G-Z2EK650VQT

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: posts
      name: Tech blogs
      url: /posts/
      weight: 10
    - identifier: travel
      name: Travel blogs
      url: /travel/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production
  title: Devaraj Ranganna's blogs
  description: "My blogs"
  keywords: [Blog, Technology]
  author: Devaraj Ranganna
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  showtoc: true
  tocopen: false

  label:
    text: "urutva"
    # icon: /apple-touch-icon.png
    # iconHeight: 35

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  socialIcons:
    - name: youtube
      url:  "https://www.youtube.com/channel/UCtJyqBnw4O_KFVF1e7BZt5g"
    - name: github
      url: "https://github.com/urutva"
    - name: linkedin
      url: "https://uk.linkedin.com/in/urutva"
    - name: twitter
      url: "https://twitter.com/urutva"

  # profile-mode
  profileMode:
    enabled: true
    title: Devaraj Ranganna
    subtitle: >
              An engineer in me is passionate about open source
              and curious about everything else.

               A wanderer in me loves traveling around the world
    buttons:
      - name: Tech blogs
        url: posts
      - name: Travel blogs
        url: travel

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: false  # useSessionStorage is not supported when using Google Analytics v4 (gtag.js).
  instagram:
    disable: false
    simple: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
  vimeo:
    disable: false
    enableDNT: true
    simple: true
  youtube:
    disable: false
    privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
